version: '2.1'
volumes:
    phpsocket: {}
    phplog: {}
services:
    api:
        image: whatwedo/symfony3
        container_name: ticTacToeBot-api
#        command: /bin/sh /var/www/bin/init.sh
        environment:
            CONTAINER_TIMEZONE: ${CONTAINER_TIMEZONE}
            COMPOSER_ALLOW_SUPERUSER: 1 # Allow Composer to be run as root
        volumes:
            - ${API_PATH}:/var/www:rw
            - ${API_PATH}/var/logs/nginx:/var/log/nginx:rw
        ports:
            - "9090:80"
    client:
        image: nginx:latest
        container_name: ticTacToeBot-client
        depends_on:
            - api
        environment:
            - NGINX_PORT=80
        volumes:
            - ${CLIENT_PATH}:/usr/share/nginx/html
        ports:
            - "8080:80"
    client-tools:
        image: mkenney/npm:latest
        container_name: ticTacToeBot-clientTools
        command: /bin/sh build.sh
        depends_on:
            - client
        environment:
            - PUID=1
            - PGID=1
        volumes:
            - ${CLIENT_PATH}:/src:rw


